version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: kaddem_db
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql

  springboot-app:
    build:
      context: C:\Users\NIDHAL CHAABENE\Desktop\DevSecOps Project
    image: nidhalchaabene
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

volumes:
  db_vol: {}
